export const ADD_COOKIE = 'ADD_COOKIE';
export const GENERATE_COOKIE_FROM_PRODUCERS = 'GENERATE_COOKIE_FROM_PRODUCERS';
export const REMOVE_COOKIE = 'REMOVE_COOKIE';
export const BUY_UPGRADE = 'BUY_UPGRADE';
export const BUY_PRODUCER = 'BUY_PRODUCER';
export const SAVE_STATE = 'SAVE_STATE';
export const LOAD_STATE = 'LOAD_STATE';
